### ISSUE TITLE
make deny in access-lists red

### ISSUE THREAD

**Issue by CWempe** [woodjme/vscode-cisco-syntax#13]
I think it would make sense if the `deny` command would be highlighted in a red color like `shutdown` and `no`.

now:
![image](https://user-images.githubusercontent.com/1270359/63520577-3a8f1d00-c4f5-11e9-8c83-1be9b980f721.png)

To be frank, I think `permit` should be green, too.
But I understand green is best practice for comments and remarks. 😉

**Comment by woodjme** [comment]
Hi @CWempe 

The colour that your seeing is actually predetermined by your theme, not by the extension itself. With that said you could overwrite this rule with something like this is your `settings.json`

```json
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "support.constant.cisco",
                "settings": {
                    "foreground": "#FF0000",
                    "fontStyle": "bold underline"
                }
            },
            {
                "scope": "constant.character.escape.cisco",
                "settings": {
                    "foreground": "#15ff00",
                    "fontStyle": "bold underline"
                }
            }
        ]
    },
```

![Screenshot 2019-09-17 at 13 24 05](https://user-images.githubusercontent.com/9112373/65041332-74b1da00-d94e-11e9-82ee-1488445a2fea.png)
