### ISSUE TITLE
Extension associations

### ISSUE THREAD

**Issue by KamasamaK** [woodjme/vscode-cisco-syntax#3]
It's not good practice to take over generic file extensions like `.txt` or even `.cfg`.

**Comment by KamasamaK** [comment]
@woodjme Thanks for addressing this, but what actually affects that is the [`extensions` in package.json](https://github.com/woodjme/vscode-cisco-syntax/blob/e5219c148c54393c7e624d3a999ff3dcfa580ec8/package.json#L27). I'm pretty sure VS Code ignores those parts of the grammar.

**Comment by woodjme** [comment]
5736d67212964d0fef14a54831b0e70c4e951100

**Comment by KamasamaK** [comment]
Thanks!

A note to anyone who liked the association of those extensions: You can use the `files.associations` setting.
