### ISSUE TITLE
Cisco Syntax Highlighting not working in latest version of VSCode

### ISSUE THREAD

**Issue by dlhendry** [woodjme/vscode-cisco-syntax#5]
Hi, in my latest version of VSCode, the Cisco Syntax highlighter does not seem to be working.  Was wondering if anyone else was having this issue?  
VSCode Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Before the upgrade I was able to simply load my config files (.txt or .cfg) and they would automatically highlight the Cisco syntax.  Since that time I also installed a python extension for the same purpose. Both the PowerShell extension and the Python extension seem to work after the VSCode upgrade but I can't get the highlighting from the Cisco extension.  

Thanks for your assistance. 
Don Hendry

**Comment by woodjme** [comment]
Hi @dlhendry 

Please see #3
